<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework>
    <EnableDefaultItems>false</EnableDefaultItems><ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable><EnableNETAnalyzers>false</EnableNETAnalyzers>
    <DefineConstants Condition="'$(Candidate)' == 'true'">$(DefineConstants);CANDIDATE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Dekaf"><HintPath>$(ProductDirectory)/Dekaf.dll</HintPath></Reference>
    <Reference Include="Dekaf.Abstractions"><HintPath>$(ProductDirectory)/Dekaf.Abstractions.dll</HintPath></Reference>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <Compile Include="Loaded.cs" />
  </ItemGroup>
</Project>
