<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Confluent.Kafka" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="OpenTelemetry" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" VersionOverride="1.18.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" VersionOverride="1.18.0" />
    <PackageReference Include="System.Text.Json" VersionOverride="10.0.11" GeneratePathProperty="true" />
  </ItemGroup>

  <Target Name="CopyJsonSourceGenerator" AfterTargets="Build">
    <Copy SourceFiles="$(PkgSystem_Text_Json)\analyzers\dotnet\roslyn4.4\cs\System.Text.Json.SourceGeneration.dll"
          DestinationFolder="$(OutDir)" />
  </Target>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\**\*.csproj"
                      Exclude="..\..\src\Dekaf.SchemaRegistry.Avro.Poco.Generator\*.csproj" />
    <ProjectReference Include="..\..\src\Dekaf.SchemaRegistry.Avro.Poco.Generator\Dekaf.SchemaRegistry.Avro.Poco.Generator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
