namespace Dekaf.Protocol;

/// <summary>
/// Kafka protocol error codes.
/// </summary>
public enum ErrorCode : short
{
    UnknownServerError = -1,
    None = 0,
    OffsetOutOfRange = 1,
    CorruptMessage = 2,
    UnknownTopicOrPartition = 3,
    InvalidFetchSize = 4,
    LeaderNotAvailable = 5,
    NotLeaderOrFollower = 6,
    RequestTimedOut = 7,
    BrokerNotAvailable = 8,
    ReplicaNotAvailable = 9,
    MessageTooLarge = 10,
    StaleControllerEpoch = 11,
    OffsetMetadataTooLarge = 12,
    NetworkException = 13,
    CoordinatorLoadInProgress = 14,
    CoordinatorNotAvailable = 15,
    NotCoordinator = 16,
    InvalidTopicException = 17,
    RecordListTooLarge = 18,
    NotEnoughReplicas = 19,
    NotEnoughReplicasAfterAppend = 20,
    InvalidRequiredAcks = 21,
    IllegalGeneration = 22,
    InconsistentGroupProtocol = 23,
    InvalidGroupId = 24,
    UnknownMemberId = 25,
    InvalidSessionTimeout = 26,
    RebalanceInProgress = 27,
    InvalidCommitOffsetSize = 28,
    TopicAuthorizationFailed = 29,
    GroupAuthorizationFailed = 30,
    ClusterAuthorizationFailed = 31,
    InvalidTimestamp = 32,
    UnsupportedSaslMechanism = 33,
    IllegalSaslState = 34,
    UnsupportedVersion = 35,
    TopicAlreadyExists = 36,
    InvalidPartitions = 37,
    InvalidReplicationFactor = 38,
    InvalidReplicaAssignment = 39,
    InvalidConfig = 40,
    NotController = 41,
    InvalidRequest = 42,
    UnsupportedForMessageFormat = 43,
    PolicyViolation = 44,
    OutOfOrderSequenceNumber = 45,
    DuplicateSequenceNumber = 46,
    InvalidProducerEpoch = 47,
    InvalidTxnState = 48,
    InvalidProducerIdMapping = 49,
    InvalidTransactionTimeout = 50,
    ConcurrentTransactions = 51,
    TransactionCoordinatorFenced = 52,
    TransactionalIdAuthorizationFailed = 53,
    SecurityDisabled = 54,
    OperationNotAttempted = 55,
    KafkaStorageError = 56,
    LogDirNotFound = 57,
    SaslAuthenticationFailed = 58,
    UnknownProducerId = 59,
    ReassignmentInProgress = 60,
    DelegationTokenAuthDisabled = 61,
    DelegationTokenNotFound = 62,
    DelegationTokenOwnerMismatch = 63,
    DelegationTokenRequestNotAllowed = 64,
    DelegationTokenAuthorizationFailed = 65,
    DelegationTokenExpired = 66,
    InvalidPrincipalType = 67,
    NonEmptyGroup = 68,
    GroupIdNotFound = 69,
    FetchSessionIdNotFound = 70,
    InvalidFetchSessionEpoch = 71,
    ListenerNotFound = 72,
    TopicDeletionDisabled = 73,
    FencedLeaderEpoch = 74,
    UnknownLeaderEpoch = 75,
    UnsupportedCompressionType = 76,
    StaleBrokerEpoch = 77,
    OffsetNotAvailable = 78,
    MemberIdRequired = 79,
    PreferredLeaderNotAvailable = 80,
    GroupMaxSizeReached = 81,
    FencedInstanceId = 82,
    EligibleLeadersNotAvailable = 83,
    ElectionNotNeeded = 84,
    NoReassignmentInProgress = 85,
    GroupSubscribedToTopic = 86,
    InvalidRecord = 87,
    UnstableOffsetCommit = 88,
    ThrottlingQuotaExceeded = 89,
    ProducerFenced = 90,
    ResourceNotFound = 91,
    DuplicateResource = 92,
    UnacceptableCredential = 93,
    InconsistentVoterSet = 94,
    InvalidUpdateVersion = 95,
    FeatureUpdateFailed = 96,
    PrincipalDeserializationFailure = 97,
    SnapshotNotFound = 98,
    PositionOutOfRange = 99,
    UnknownTopicId = 100,
    DuplicateBrokerRegistration = 101,
    BrokerIdNotRegistered = 102,
    InconsistentTopicId = 103,
    InconsistentClusterId = 104,
    TransactionalIdNotFound = 105,
    FetchSessionTopicIdError = 106,
    IneligibleReplica = 107,
    NewLeaderElected = 108,
    OffsetMovedToTieredStorage = 109,
    FencedMemberEpoch = 110,
    UnreleasedInstanceId = 111,
    UnsupportedAssignor = 112,
    StaleMemberEpoch = 113,
    MismatchedEndpointType = 114,
    UnsupportedEndpointType = 115,
    UnknownControllerId = 116,
    UnknownSubscriptionId = 117,
    TelemetryTooLarge = 118,
    InvalidRegistration = 119,
    NotMemberOfTenant = 120
}

/// <summary>
/// Extension methods for ErrorCode.
/// </summary>
public static class ErrorCodeExtensions
{
    /// <summary>
    /// Returns true if the error indicates the request should be retried.
    /// </summary>
    public static bool IsRetriable(this ErrorCode errorCode) => errorCode switch
    {
        ErrorCode.CorruptMessage => true,
        ErrorCode.UnknownTopicOrPartition => true,
        ErrorCode.LeaderNotAvailable => true,
        ErrorCode.NotLeaderOrFollower => true,
        ErrorCode.RequestTimedOut => true,
        ErrorCode.ReplicaNotAvailable => true,
        ErrorCode.NetworkException => true,
        ErrorCode.CoordinatorLoadInProgress => true,
        ErrorCode.CoordinatorNotAvailable => true,
        ErrorCode.NotCoordinator => true,
        ErrorCode.NotEnoughReplicas => true,
        ErrorCode.NotEnoughReplicasAfterAppend => true,
        ErrorCode.NotController => true,
        ErrorCode.KafkaStorageError => true,
        ErrorCode.FetchSessionIdNotFound => true,
        ErrorCode.InvalidFetchSessionEpoch => true,
        ErrorCode.FencedLeaderEpoch => true,
        ErrorCode.OffsetNotAvailable => true,
        ErrorCode.PreferredLeaderNotAvailable => true,
        ErrorCode.EligibleLeadersNotAvailable => true,
        ErrorCode.UnstableOffsetCommit => true,
        ErrorCode.OutOfOrderSequenceNumber => true,
        ErrorCode.ThrottlingQuotaExceeded => true,
        _ => false
    };

    /// <summary>
    /// Returns true if the error indicates an invalid metadata state.
    /// </summary>
    public static bool RequiresMetadataRefresh(this ErrorCode errorCode) => errorCode switch
    {
        ErrorCode.UnknownTopicOrPartition => true,
        ErrorCode.LeaderNotAvailable => true,
        ErrorCode.NotLeaderOrFollower => true,
        ErrorCode.BrokerNotAvailable => true,
        ErrorCode.ReplicaNotAvailable => true,
        ErrorCode.CoordinatorNotAvailable => true,
        ErrorCode.NotCoordinator => true,
        ErrorCode.NotController => true,
        ErrorCode.FencedLeaderEpoch => true,
        ErrorCode.UnknownLeaderEpoch => true,
        _ => false
    };
}
