namespace Dekaf.Protocol.Messages;

/// <summary>
/// AlterUserScramCredentials request (API key 51).
/// Alters SCRAM credentials for users.
/// </summary>
public sealed class AlterUserScramCredentialsRequest : IKafkaRequest<AlterUserScramCredentialsResponse>
{
    public static ApiKey ApiKey => ApiKey.AlterUserScramCredentials;
    public static short LowestSupportedVersion => 0;
    public static short HighestSupportedVersion => 0;

    /// <summary>
    /// The SCRAM credential deletions.
    /// </summary>
    public IReadOnlyList<ScramCredentialDeletion>? Deletions { get; init; }

    /// <summary>
    /// The SCRAM credential upsertions.
    /// </summary>
    public IReadOnlyList<ScramCredentialUpsertion>? Upsertions { get; init; }

    public static bool IsFlexibleVersion(short version) => true;
    public static short GetRequestHeaderVersion(short version) => 2;
    public static short GetResponseHeaderVersion(short version) => 1;

    public void Write(ref KafkaProtocolWriter writer, short version)
    {
        // Deletions: COMPACT_ARRAY
        var deletions = Deletions ?? [];
        writer.WriteCompactArray(
            deletions,
            static (ref KafkaProtocolWriter w, ScramCredentialDeletion d, short v) => d.Write(ref w, v),
            version);

        // Upsertions: COMPACT_ARRAY
        var upsertions = Upsertions ?? [];
        writer.WriteCompactArray(
            upsertions,
            static (ref KafkaProtocolWriter w, ScramCredentialUpsertion u, short v) => u.Write(ref w, v),
            version);

        writer.WriteEmptyTaggedFields();
    }
}

/// <summary>
/// SCRAM credential deletion entry for AlterUserScramCredentials request.
/// </summary>
public sealed class ScramCredentialDeletion
{
    /// <summary>
    /// The user name.
    /// </summary>
    public required string Name { get; init; }

    /// <summary>
    /// The SCRAM mechanism (1 = SCRAM-SHA-256, 2 = SCRAM-SHA-512).
    /// </summary>
    public required byte Mechanism { get; init; }

    public void Write(ref KafkaProtocolWriter writer, short version)
    {
        writer.WriteCompactString(Name);
        writer.WriteUInt8(Mechanism);
        writer.WriteEmptyTaggedFields();
    }
}

/// <summary>
/// SCRAM credential upsertion entry for AlterUserScramCredentials request.
/// </summary>
public sealed class ScramCredentialUpsertion
{
    /// <summary>
    /// The user name.
    /// </summary>
    public required string Name { get; init; }

    /// <summary>
    /// The SCRAM mechanism (1 = SCRAM-SHA-256, 2 = SCRAM-SHA-512).
    /// </summary>
    public required byte Mechanism { get; init; }

    /// <summary>
    /// The number of iterations (must be at least 4096).
    /// </summary>
    public required int Iterations { get; init; }

    /// <summary>
    /// A random salt generated by the client.
    /// </summary>
    public required byte[] Salt { get; init; }

    /// <summary>
    /// The salted password.
    /// </summary>
    public required byte[] SaltedPassword { get; init; }

    public void Write(ref KafkaProtocolWriter writer, short version)
    {
        writer.WriteCompactString(Name);
        writer.WriteUInt8(Mechanism);
        writer.WriteInt32(Iterations);
        writer.WriteCompactBytes(Salt);
        writer.WriteCompactBytes(SaltedPassword);
        writer.WriteEmptyTaggedFields();
    }
}
